apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ahmednaveeed/prepai-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: DATABASE_URL
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: OPENAI_API_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: SECRET_KEY
            - name: ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: ALGORITHM
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: ACCESS_TOKEN_EXPIRE_MINUTES

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort